export const recepieDAta = {
  title: "Fluffy Maida Pancakes",
  description:
    "Light and airy pancakes made from all-purpose flour, perfect for a delightful breakfast.",
  ratings: 0,
  author: "Abhishek Gupta",
  addedBy: "Abhishek Gupta",
  prepTime: "10 mins",
  cookTime: "15 mins",
  dateAdded: "1/23/2025",
  difficulty:'easy',
  cuisine:"japanese",
  nutrients: null,
  servings: 4,
  isFavourite: true,
  image:
  "https://media.istockphoto.com/id/1973211564/photo/blank-recipe-card-mockup-on-white-wooden-table.jpg?s=1024x1024&w=is&k=20&c=gc4Uw1UdYkZ80hBWHD2gQ2GDI8tC0X8sHg_JKPEA6O8=",
  ingredients: [
    "1 cup all-purpose flour (maida)",
    "2 tablespoons sugar",
    "1 teaspoon baking powder",
    "½ teaspoon baking soda",
    "¼ teaspoon salt",
    "1 cup buttermilk",
    "1 large egg",
    "2 tablespoons melted butter",
    "1 teaspoon vanilla extract",
    "Butter or oil for cooking",
  ],
  shoppingList: true,
  steps: [
    "In a large mixing bowl, combine the all-purpose flour, sugar, baking powder, baking soda, and salt. Whisk together until well mixed.",
    "In another bowl, whisk together the buttermilk, egg, melted butter, and vanilla extract until smooth.",
    "Pour the wet ingredients into the dry ingredients and gently fold them together using a spatula. Be careful not to overmix; a few lumps are okay.",
    "Let the batter rest for about 10 minutes while you preheat your skillet or griddle over medium heat.",
    "Add a little butter or oil to the skillet to prevent sticking. Once hot, pour 1/4 cup of batter onto the skillet for each pancake.",
    "Cook the pancake for about 2-3 minutes, or until bubbles form on the surface and the edges look set. Flip the pancake and cook for another 1-2 minutes until golden brown.",
    "Remove the pancake from the skillet and keep warm. Repeat with the remaining batter, adding more butter or oil as needed.",
  ],
};
